# Generated by Django 5.2.5 on 2026-01-03 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joberror',
            name='raw_data',
        ),
        migrations.AlterField(
            model_name='joberror',
            name='error_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joberror',
            name='row_index',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('enriched_data', models.JSONField(blank=True, null=True)),
                ('is_enriched', models.BooleanField(default=False)),
                ('confidence_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='jobs.etljob')),
            ],
        ),
    ]
